yatube/about/urls.py
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path(
        'create/',
        views.post_create, name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit, name='post_edit'
    ),
    path(
        'follow/',
        views.follow_index, name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow, name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.forbidden'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/card_posts.html
{% load thumbnail %}
<article>
  <ul>
    {% if show_author %}
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author.username %}">
        все посты пользователя
      </a>
    </li>
    {% endif %}
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <p>
    <a href="{% url 'posts:post_detail' post.id %}">
      подробная информация
    </a>
  </p>
  {% if post.group %}
    {% if show_group %}
    <p>
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    </p>
    {% endif %}
  {% endif %}
</article>

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">&#169; {{ year }} Copyright
  <p><span style="color:red">Ya</span>tube</p>
</div>

yatube/templates/includes/form_errors.html
{% for field in form %}
   {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}

yatube/templates/includes/form_field.html
{% load user_filters %}
<div class="form-group row my-3"
  {% if field.field.required %} 
    aria-required="true"
  {% else %}
    aria-required="false"
  {% endif %}
  >
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
  </label>
  {{ field|addclass:'form-control' }} 
  {% if field.help_text %}
    <small 
      id="{{ field.id_for_label }}-help"
      class="form-text text-muted">
      {{ field.help_text|safe }}
    </small>
  {% endif %}
</div>

yatube/templates/includes/header.html
{% load static %}

{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills"> 
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
            href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" 
            href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
            href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}
  

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/switcher.html
{% with request.resolver_match.view_name as view_name %}
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if view_name  == 'posts:index' %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if view_name  == 'posts:follow_index' %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}
{% endwith %}